.vscode/settings.json, experimental/include/experimental/tools/handshake-simulator/ExecModels.h, experimental/tools/handshake-simulator/ExecModels.cpp, experimental/tools/handshake-simulator/Simulation.cpp
This PR mainly addresses the problem that the handshake simulator buffers weren't the Dynamatic buffers at all. This led to the creation of a way of having a rising edge abstraction in the code simulation.
- Added OEHB and TEHB buffers (OPAQUE and FIFO)
- Added a multicycle system with a syntax close to VHDL
- Changed dataflow states system to easier and cleaner booleans
Soon enough, it will be possible to add OEHB and TEHB in execution models, without having those buffers as instructions.
=> [handshake-sim] Added buffers and rising edge abstractions

tools/export-vhdl/src/StringUtils.cpp
This PR fixes the constant width problem of the legacy dot2vhdl/export-vhdl tools described in #54 ; this allows us to support constant value that has bit-width 17--32.
=> [export-vhdl] fixing the handling of constant widths in the export-vhdl tool

data/components.json
This commit/PR removes the incorrect characterization of the extsi unit, which might cause the buffering algorithm to add unnecessary buffers for controlling the critical path
=> [Data] removing the characterization of extsi units

experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp, experimental/test/lib/Transforms/Speculation/commit-test.mlir, experimental/test/lib/Transforms/Speculation/placement-finder-test.mlir, experimental/test/lib/Transforms/Speculation/save-commit-test.mlir, experimental/test/lib/Transforms/Speculation/save-test.mlir, include/dynamatic/Dialect/Handshake/HandshakeOps.td, lib/Support/CFG.cpp
This PR addresses several issues regarding the speculation implementation:
- Add the `$enable` control signal of type `NoneType` to SpeculatorOp, which is responsible for enabling the Speculator.
- Add automatic connection of the enable signal to the edge from a predecessor BB carrying the control signal of `NoneType`.
- Improve the commit-control routing, where the specTag after a branch isn't merged, but rather forked from the input.
- Fix the tests for speculation passes to include the new enable signal and adapting to the new naming system.
- Fix a bug in `CFG.cpp:getBBPredecessorArcs` where not initializing `BBEndpoints` could lead to unexpected errors.
=> [Speculation] Add Enable signal to Speculator and other small fixes

tools/dynamatic/dynamatic.cpp, tools/dynamatic/scripts/compile.sh
Modified the frontend script of dynamatic to add the command to set the polygeist path. 
The script compile.sh receives as input this path. If not specified, the script will look for the default location of polygeist (i.e., inside dynamatic main folder)
=> [Frontend] Add set-polygeist-path command in dynamatic frontend

tools/dynamatic/dynamatic.cpp, tools/dynamatic/scripts/compile.sh
This PR moves the logic that checks if polygeist path is set from `compile.sh` to the frontend. There are two reasons for this change:
1. Keep the shell script as simple as possible.
2. If the polygeist path is empty and there are extra arguments after it, the positional argument $7 will not be an empty string, but rather the argument behind it.
A concrete example:
```
return execCmd(script, state.dynamaticPath, state.getKernelDir(),
state.getOutputDir(), state.getKernelName(), buffers,
floatToString(state.targetCP, 3), state.polygeistPath, use_sharing);
```
If there `state.polygeistPath` is an empty string, then the arguments passed to the shell script would be (the paths are simplified):
```
dynamatic dynamatic/integration-test/fir dynamatic/integration-test/fir/out fir 0 5.000 0
```
So …
=> [Frontend] move polygeist check logic to frontend

data/verilog/arith/muli.v, data/verilog/handshake/dataless/oehb.v, data/verilog/handshake/dataless/tehb.v, data/verilog/handshake/mem_controller_loadless.v, data/verilog/handshake/oehb.v, data/verilog/handshake/tehb.v, data/verilog/support/dataless/elastic_fifo_inner.v, data/verilog/support/eager_fork_register_block.v, data/verilog/support/elastic_fifo_inner.v, data/verilog/support/mc_support.v, data/vhdl/arith/select.vhd, data/vhdl/handshake/dataless/oehb.vhd, data/vhdl/handshake/dataless/tehb.vhd, data/vhdl/handshake/mem_controller_loadless.vhd, data/vhdl/handshake/oehb.vhd, data/vhdl/handshake/tehb.vhd, data/vhdl/support/dataless/elastic_fifo_inner.vhd, data/vhdl/support/delay_buffer.vhd, data/vhdl/support/eager_fork_register_block.vhd, data/vhdl/support/elastic_fifo_inner.vhd, data/vhdl/support/mc_support.vhd
This commit makes two changes to all HDL modules:
1. Making all resets of dataflow units consistent.
2. Making all resets synchronous (same as Vivado HLS).
=> [HDL] Making all FF resets consistent

data/components.json, lib/Support/TimingModels.cpp
`9dbd9db` introduces the handshake version of all arith units in Dynamatic. It overlooked that the timing model library should also be changed. This PR fixes that.
Testing:
- Currently running FPL22 buffers on all VHDL benchmarks.
=> [TimingModels] fix timing model library and retrieve logic

data/vhdl/handshake/join.vhd
Commit `305f995` introduced a join operation
which can be lowered to the RTL. Due to a typo
the component cannot be instantiated, leading to
errors in modelsim (_recursive instantiation_).
=> [RTL] Fix in `join_handshake`

include/dynamatic/Transforms/HandshakeOptimizeBitwidths.h, include/dynamatic/Transforms/Passes.td, lib/Transforms/HandshakeOptimizeBitwidths.cpp, test/Transforms/HandshakeOptimizeBitwidths/bound-opti.mlir, test/Transforms/HandshakeOptimizeBitwidths/handshake-special.mlir, tools/dynamatic/scripts/compile.sh, tools/dynamatic/scripts/simulate.sh, tools/hls-verifier/src/HlsCoVerification.cpp, tools/hls-verifier/src/HlsVhdlTb.cpp, tools/hls-verifier/src/HlsVhdlVerification.cpp, tools/hls-verifier/src/VerificationContext.h
Currently, all our address-carrying channels in the IR and in the final circuit are hardcoded so that their data signal is 32-bits. Since Dynamatic enforces the size of all memories to be known at compile-time, we have the opportunity to thin out these signals to the bare minimum number of bits necessary to index into each particular memory region.
This commit adds this optimization to the default compilation flow so that all Dynamatic-generated circuits can benefit from it. Main changes are detailed below.
- The `--handshake-optimize-bitwidths` flag looses its "legacy" flag which was previously used to explicitly disable this optimization when we still depended on legacy Dynamatic's toolchain for RTL export. The pass's address-optimization-related rewrite patterns are also …
=> [HandshakeOptimizeBitwidths] Optimize width of address-carrying channels

data/verilog/support/elastic_fifo_inner.v, tools/dynamatic/dynamatic.cpp, tools/dynamatic/samples/fir.dyn, tools/dynamatic/scripts/compile.sh
Changes:
- Frontend option for different buffer placement algorithms;
- Reset the memory content of the elastic FIFO inner module on power-up.
---
Since we plan to integrate more buffer algorithms (at least two by the end of the year), it is useful to have a switch that explicitly chooses the different buffer algorithms to use.
Possible options:
```
dynamatic> compile --buffer-algorithm on-merges
dynamatic> compile --buffer-algorithm fpga20
dynamatic> compile --buffer-algorithm fpl22
```
Also, I noticed that the algorithm names are quite non-intuitive---it is clear to us what these options mean, but not for a new developer (e.g., what does fpl22 even mean?).
=> [Frontend] Buffer placement option in the compile command

experimental/test/lib/Transforms/Speculation/annotate-test.mlir, experimental/test/lib/Transforms/Speculation/commit-test.mlir, experimental/test/lib/Transforms/Speculation/placement-finder-test.mlir, experimental/test/lib/Transforms/Speculation/save-commit-test.mlir, experimental/test/lib/Transforms/Speculation/save-test.mlir, include/dynamatic/Dialect/Handshake/HandshakeOps.td, lib/Dialect/Handshake/HandshakeOps.cpp
Now:
- can successfully place a speculator to `integration-test/fir/out/comp/handshake_export.mlir` at `cmpi1#0`
- all tests passed when running `ninja check-dynamatic-experimental` 
Fixes:
1. A bug in SpeculatorOp::parse (the order of arguments was wrong)
2. Relaxed types from ChannelType to HandshakeType to support control tokens as well
1. Handshake_SpecOp dataIn/Out
2. Speculator dataIn/Out
3. SpeculatingBranch dataOperand, trueResult, falseResult
3. Changed the type of SpeculatingBranch's tagFromOperand arg
- Previously BoolChannel, changed to HandshakeChannel
4. Updated test MLIR files under `experimental/test/lib/Transforms/Speculation` to use the latest type system
- Didn't change CHECKS comments but all tests passed
=> Fixed HandshakeSpeculationPass

data/vhdl/handshake/control_merge.vhd
I'm working on adding a spec bit on each RTL module.
I found that the current control_merge.vhd didn't work, so I fixed this.
Note: control_merge.vhd will be referenced by the *dataless* version of control_merge *with a spec bit*, as it treats the extra bit as 1-bit data.
=> [RTL] fixed control_merge.vhd

lib/Transforms/ForceMemoryInterface.cpp
This PR fixes the `--force-memory-interface` pass.
Without this change, the memory operation would have two separate attributes: handshake.mem_interface and mem_interface. And somehow one of them will be ignored (and it is not clear which one is ignored).
To test this, change the following lines in `compile.sh`:
```diff
"$DYNAMATIC_OPT_BIN" "$F_HANDSHAKE" \
-  --handshake-analyze-lsq-usage --handshake-replace-memory-interfaces \
+  --handshake-analyze-lsq-usage \
+  --handshake-replace-memory-interfaces \
```
---
Also, should we use `setDialectAttr(...)` everywhere in the codebase to avoid things like this?
=> [ForceMemoryInterface] fix attribute setting logic.

docs/Tutorials/CreatingPasses/2.WritingASimplePass.md
In the new version of dynamatic the contents related to the PassCreation tutorial are in the CreatingPasses directory. I've updated the tutorial according to this change. I've also removed circt which is not there anymore. Lastly, there is a change in one of the CMakeLists.
=> Updating PassCreation tutorial to fit the new version of dynamatic

experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp
The connection of SCCommitCtrl from the speculator to save-commit units was slightly different from Haoran's thesis, which caused a deadlock. Thus I updated the implementation to match that of Haoran's thesis.
Also, I fixed the names of branch ops to make them more understandable ( #169 ).
The rename of `SCBranchCtrl` to `SCIsMisspec` is not done here because it involves the change in the backend.
Now the connection would be like this:
=> [SpeculationPass] Fixed SCCommitCtrl connection

data/verilog/arith/select.v
The empty parameter list in select.v  fails to parse in iverilog:
```text
PARSING INPUT
./out_noctrl/hdl/selector.v:2: syntax error
I give up.
```
=> [Verilog] Fix syntax error in select.v

experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp
Background: The speculator needs a signal to determine the timing of the speculation, just as constant units need a control signal.
The speculator makes a speculation every time the BB it belongs to is triggered; thus the signal should be routed from the speculator's BB itself so that it indicates the start of the BB.
Before: the enable signal of the speculator was routed from the previous BB (bug).
After: it will be from the control network in the same BB, just before CBranch.
And the name of the former enable signal is changed to "trigger signal".
(If I should place a figure here I will do that. It will be similar to Fig. 34 of Haoran's thesis)
=> [SpeculationPass] Fixed the enable signal of speculator

README.md
This is to document the behavior described by @Jiahui17 in #164. This should not be considered a solution to the issue, but it is necessary to document this caveat for the sake of new users until it is fixed.
=> [docs] ninja check-dynamatic behavior documentation

include/dynamatic/Analysis/ControlDependenceAnalysis.h, lib/Analysis/CMakeLists.txt, lib/Analysis/ControlDependenceAnalysis.cpp
The control dependence analysis is a further step into #177. 
The analysis answers the following question: "Given a block `bb` in the CFG, which are the blocks whose control decisions impact the execution of `bb`"?
The analysis can be applied on an IR with an underlying CFG (both `cf` and `handshake` before it gets flattened). 
The implementation comes directly from its definition in the following paper:
_Jeanne Ferrante, Karl J. Ottenstein, and Joe D. Warren. 1987. The program dependence graph and its use in optimization. ACM Trans. Program. Lang. Syst. 9, 3 (July 1987), 319–349. https://doi.org/10.1145/24039.24041_
=> [Analysis] Control Dependence Analysis

build.sh, docs/AdvancedBuild.md
As is noted in the documentation, linking LLVM can easily run out of memory/drive the system into swap.
LLVM's CMake setup actually provides a mechanism for limiting the max number of parallel link jobs to prevent exactly this issue.
See `LLVM_PARALLEL_{COMPILE,LINK}_JOBS:STRING` here: https://llvm.org/docs/CMake.html#llvm-specific-variables
This patch exposes this option in the ./build.sh script and sets an optimistic default of 4 maximum link jobs.
LLVM's docs recommend a limit of 1 link job per 15GB of RAM. The proposed default of 4 works well on my (64GB) machine, but maybe a different default behaviour (no limit? lower limit?) is better.
=> [build.sh] Expose LLVM's parallel link job throttling.

tools/hls-verifier/src/CAnalyser.cpp, tools/hls-verifier/src/HlsCoVerification.cpp, tools/hls-verifier/src/HlsVhdlTb.cpp, tools/hls-verifier/src/HlsVhdlVerification.cpp, tools/hls-verifier/src/Utilities.cpp, tools/hls-verifier/src/Utilities.h, tools/hls-verifier/src/VerificationContext.cpp
As @Jiahui17 suggested while discussing #179, this PR is to fix style inconsistencies in the HLS verifier according to these [guidelines](https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements).
=> [hls-verifier] Fixed brace style inconsistencies

data/rtl-config-vhdl.json
The executable `python` does not always exist: we need to install `python-is-python3` to get it (the package might have a different name on other distros).
Fixes #220
=> [Backend] Fix LSQ entry in rtl-config

data/verilog/support/dataless/merge_notehb.v, tools/dynamatic/scripts/synthesize.sh
Commit `ebf54e81` introduces a bug in the component 
`merge_notehb_dataless` (verilog) which does not allow
neither the simulation nor the synthesis with verilog.
This commit fixes such issue, relying on the same
technique used in #211 to fix the synthesis of the control 
merge component.
Also, the synthesis script is updated to get rid
of a command which was obsolete with respect to
the current structure of exported HDL files.
Close #149.
=> [HDL] Fix verilog HDL generation

data/verilog/handshake/mem_controller_loadless.v, data/verilog/handshake/store.v, data/vhdl/handshake/mem_controller_loadless.vhd, data/vhdl/handshake/store.vhd
Fix the throughput problem (see #199) related to the store port and LSQ. Now the memory interface (LSQ|MC) synchronizes the data and address tokens.
Changes:
- [store.{vhd,v}]: Remove the join (excessive synchronization for LSQ).
- [mem_controller_loadless.{vhd,v}]: Add join to make sure that store is issued when both data and address are ready.
fixes #199
=> [Verilog][VHDL] Removing Join from HDL Implementation of Store.{vhd,v}

.github/workflows/c-cpp.yml
Quick patch to prevent unnecessarily running the CI/CD pipeline on draft pull requests.
=> [Tools] Added check in Actions to prevent running on draft PRs

README.md, test/lit.cfg.py, test/lit.site.cfg.py.in
Currently, when building in release mode, the unit test `invalid.mlir` fails, due to mlir rising a segmentation fault rather than the expected error message. 
On the one hand, we cannot get rid of this test, since it is actually useful to validate the handshake dialect, and it still runs correctly in debug mode.
On the other hand, it's important to have a working test suite, to be integrated in the CI/CD pipeline. 
This PR fixes the problem by relying on a CMAKE macro to know whether the project was built in release or debug mode, and possibly skipping `invalid.mlir` when generating the test scripts through `ninja`. 
I marked this PR as draft as I'd like to get some feedbacks from your sides regarding the validity of such a mechanism :)
Also closes #164 .
=> [Test] Skip invalid test when building in release mode

data/rtl-config-vhdl.json, tools/integration/ignored_tests.txt
In the VHDL configuration, `sitofp` and `fptosi` (#134 )
lacked of some component dependencies. 
This caused the their instantiation to fail during simulation.
Such a fix allows the test `matching_2` to work.
By double-checking all the other tests, `float_basic` was
also erroneously marked as failing.
=> [HDL] Missed dependencies in floating point operations

tools/export-rtl/export-rtl.cpp
Merry Christmas!
I noticed a small bug where an instance of `RTLMatch` isn't being deleted.
@lucas-rami Please review this!
=> [export-rtl] fix: delete match when it's not collected by externals

tools/integration/run_integration.py
This PR fixes some issues with the integration test script:
1. Fixed issue where the script would not work if called with a working directory different from `tools/integration`.
2. Fixed issue where tests that are located within subdirectories (e.g. `integration-test/memory/test_memory_1/test_memory_1.c`) would not be correctly filtered when using `--list` and `--ignore`.
3. Removed instances of f-strings that were incompatible with Python versions older than 3.12, e.g.
```py
print(f"The result is {
result}")
``` 
is valid since 3.12 (see [this Python doc](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep701)), but would raise an error in older versions.
=> [Tools] Integration script patch

data/verilog/arith/select.v
The following commit fixes a bug present in the select module in the Verilog version.
=> [HDL][Verilog] Bug in the select module

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
The `getDiscriminatedModName` function ensures that module names are unique, preventing duplicate RTL module definitions.  
Consider the following scenario:  
- Two `ConstantOp`s (`constant0` and `constant1`) have identical operand and result types.  
- When `constant0` is translated from Handshake IR to HW IR, an external module is created for it.  
- When `constant1` is translated, the external module is reused by calling `getDiscriminatedModName`, which returns the same name as before.  
Currently, `getDiscriminatedModName` only considers the op name and attributes (e.g., `DATA_TYPE`, `FIFO_DEPTH`). However, `ConstantOp` does not fully encode its control operand and result types to its attributes. This leads to incorrect aliasing when distinct types—such as `channel<i1>` and …
=> [HandshakeToHW] Fixed getDiscriminatedModName to Properly Differentiate Modules

include/dynamatic/Support/RTL/RTL.h, lib/Support/RTL/RTL.cpp, tools/export-rtl/export-rtl.cpp
The `DATA_TYPE` attribute is commonly used by most operations to pass type information to the generator or generic RTL file. However, for complex operations like `MuxOp` or `CMergeOp`, a single-type attribute may not be sufficient, as it needs to convey type information for multiple operands.  
To address this, we introduce a new parameter called `PORT_TYPES`, which stores type information for all results and operands  in a serialized JSON string.  
For a `cmpi` operation:  
```json
{"lhs": "!handshake.channel<i32, [spec: i1]>", "rhs": "!handshake.channel<i32, [spec: i1]>", "result": "!handshake.channel<i1, [spec: i1]>"}
```  
For a `mux` operation (with two inputs):  
```json
{"index": "!handshake.channel<i1>", "ins_0": "!handshake.channel<i32>", "ins_1": "!handshake.channel<i32, [spec: …
```
=> [export-rtl] PORT_TYPES parameter

include/dynamatic/Support/RTL/RTLTypes.h, lib/Support/RTL/RTLTypes.cpp
The `TIMING` attribute is now passed to the new RTL generator, which is being developed in #270 (for SMV) and #274 (for VHDL Signal Manager), particularly when a buffer is generated.  
To pass an attribute to a generator, it must be serializable—i.e., convertible into a string.  
Each attribute (e.g., `TIMING`, `DATA_TYPE`, `FIFO_DEPTH`) has an associated `RTLType` (Lucas's concept). Other `RTLType`s (such as `RTLStringType` and `RTLUnsignedType`) already provide a `serialize` method, but `RTLTimingType`, which is used for the `TIMING` attribute, did not.  
I implemented `serialize` method for `RTLTimingType`. The format is the same as the assembly format of `TimingAttr`, which can be seen in the Handshake IR files. I adjusted the format to ensure it can be easily passed to the …
=> [export-rtl] Implement serialize method for RTLTimingType

experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp, include/dynamatic/Dialect/Handshake/HandshakeOps.td, include/dynamatic/Dialect/Handshake/HandshakeTypes.h, include/dynamatic/Dialect/Handshake/HandshakeTypes.td, lib/Dialect/Handshake/HandshakeOps.cpp, lib/Dialect/Handshake/HandshakeTypes.cpp, test/Dialect/Handshake/invalid.mlir
Building on #225, I added additional type verification constraints specific to speculation. One newly introduced constraint, however, remains general: `AllExtraSignalsMatchExcept`.
- This constraint functions like `AllExtraSignalsMatch`, but ignores a specified extra signal. For example: `AllExtraSignalsMatchExcept<"spec", ["dataIn", "dataOut"]>`.
- I implemented `AllExtraSignalsMatchExcept` in `HandshakeTypes.cpp` instead of `HandshakeTypeInterfaces.td`, as I found this improves readability. If needed, I can move the implementation of other constraints to the `.cpp` file for consistency.
Other changes:
- Implemented two speculation-specific constraints: `HasSpecTag` and `LacksSpecTag`.
- Applied these constraints to speculative units, leading to a slight change in their assembly format …
=> [Speculation] Type Verification for Speculation

docs/ExtraSignalsTypeVerification.md, include/dynamatic/Dialect/Handshake/HandshakeArithOps.td, include/dynamatic/Dialect/Handshake/HandshakeInterfaces.h, include/dynamatic/Dialect/Handshake/HandshakeInterfaces.td, include/dynamatic/Dialect/Handshake/HandshakeOps.td, include/dynamatic/Dialect/Handshake/HandshakeTypes.td, lib/Dialect/Handshake/HandshakeInterfaces.cpp, lib/Dialect/Handshake/HandshakeOps.cpp
- Replaced `SameExtraSignalsInterface` with `AllExtraSignalsMatch` from #225.
- Replaced type constraints on data types (e.g., `IntChannel`, `BoolChannel`) and extra signals (e.g., `SimpleChannel`) with appropriate traits (`IsIntChannel`, `IsIntSizedChannel`, `IsSimpleHandshake`), as outlined in #279.
Close #279 .
=> [Handshake] Cleaned up type constraints

include/dynamatic/Dialect/Handshake/HandshakeOps.td, lib/Dialect/Handshake/HandshakeOps.cpp
- Renamed the operand from `enable` to `trigger` (as discussed in November).
- Limited `dataIn`/`dataOut` to `ChannelType` (previously `HandshakeType`)
- Replaced the custom assembly format for speculator with a declarative assembly format, as the custom format didn’t provide significant benefits.
- The custom format was originally used to reduce IR redundancy, as control signals like `saveCtrl` and `commitCtrl` shared the same type.
- Since `IsIntSizedChannel<1, "save(commit)Ctrl">` is specified, the custom format was halfway - it allows further simplification (removing type printing entirely). But I felt this was excessive—these types should be known from the IR.
- Given that redundancy isn’t a major downside, I opted to print the types explicitly in the IR instead.
=> [Speculator] Refactor SpeculatorOp

experimental/include/experimental/Transforms/Passes.td, experimental/lib/Transforms/ResourceSharing/Crush.cpp, include/dynamatic/Transforms/BufferPlacement/FPGA20Buffers.h, include/dynamatic/Transforms/Passes.td, lib/Transforms/BufferPlacement/FPGA20Buffers.cpp, lib/Transforms/BufferPlacement/HandshakePlaceBuffers.cpp
Removing fpga20-legacy from FPGA20buffers (and passes dependent on that one).
This option simulates the behavior of FPGA20 buffer placement in legacy Dynamatic, that one channel can have up to one buffer placed. 
Removing this because:
- It is no longer needed by any flow now.
- Adding code overhead to the extract result logic in FPGA 20.
=> [Buffers] rm legacy placement flag in FPGA20buffers

include/dynamatic/Integration.h
`std::setfill()` is included in `<iomanip>`. This header is sometimes included by default by `clang++` (e.g., included by the header files shipped by the Debian). 
This PR adds the header explicitly to avoid surprises when using the `clang++` compiled on a non-Debian distro.
=> [Integration] Add missing .h for std::setfill()

include/dynamatic/Dialect/Handshake/HandshakeOps.td
Added missing `HasSpecTag` constraints to `Speculator` and `SaveCommit`.
These constraints ensure that both the operand and result have a valid speculation tag—i.e., a downstream tag with a bitwidth of 1.
=> [Speculation] Enforce HasSpecTag Constraints in Speculator/SaveCommit

experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp, include/dynamatic/Dialect/Handshake/HandshakeOps.td
Closes #169.
`SCIsMisspec` describes what the signal represents briefly.
=> [Speculation] Renamed SCBranchCtrl to SCIsMisspec

tools/export-dot/export-dot.cpp
The color of buffers: lightgreen -> green
fixes #328
=> [export-dot] Compatible with graphviz <= 2.40.1

.github/workflows/c-cpp.yml
This adds steps that run `ninja check-dynamatic` and `ninja check-dynamatic-experimental` to the Actions workflow. It also makes sure that the integration tests run regardless whether the new steps fail.
=> [CI] Added ninja check-dynamatic

lib/Support/RTL/RTL.cpp
`oehb` and `tehb` were swapped. Sorry everyone!
=> [export-rtl] Fixed Transparent Parameter

experimental/tools/unit-generators/vhdl/generators/handshake/merge.py, experimental/tools/unit-generators/vhdl/generators/handshake/sink.py, experimental/tools/unit-generators/vhdl/generators/handshake/tfifo.py
I found some small bugs in the beta backend and fixed them:
- `merge.py` didn’t specify `bitwidth` for the dependency TEHB.
- `sink.py` didn’t handle the dataless case.
- `tfifo.py` forgot to remove a generic statement.
=> [Backend] Small bug fixes in the beta backend

data/rtl-config-vhdl-beta.json, experimental/tools/unit-generators/vhdl/generators/handshake/addf.py, experimental/tools/unit-generators/vhdl/generators/handshake/andi.py, experimental/tools/unit-generators/vhdl/generators/handshake/cmpf.py, experimental/tools/unit-generators/vhdl/generators/handshake/mulf.py, experimental/tools/unit-generators/vhdl/generators/handshake/select.py, experimental/tools/unit-generators/vhdl/generators/handshake/subf.py, experimental/tools/unit-generators/vhdl/generators/handshake/subi.py, experimental/tools/unit-generators/vhdl/vhdl-unit-generator.py, lib/Support/RTL/RTL.cpp
This PR introduces more units for the beta backend, which are used in speculation integration tests:
- `addf`
- `andi`
- `cmpf`
- `mulf`
- `select`
- `subf`
- `subi`
Note:
- There is a known bug in the signal manager of `select`, and I'll fix it after the refactoring of signal manager utility functions.
- `shli` will be added in #366.
=> [Backend] More units for beta backend

integration-test/factorial/factorial.c, integration-test/factorial/factorial.h, integration-test/iterative_division/iterative_division.c, integration-test/iterative_division/iterative_division.h, integration-test/iterative_sqrt/iterative_sqrt.c, integration-test/iterative_sqrt/iterative_sqrt.h
Benchmarks without array access are great for evaluating timing/area optimization.
=> [Integration] Benchmarks without array accesses

data/verilog/support/mc_support.v
Two changes:
- We fixed the output selection in the memory controller
- We added a default value to the `valid_out`. The default value isn't strictly needed, but it allows us to use Yosys to generate SMV from it.
=> [Verilog] write_data_signals: fix incorrect select of write data

experimental/tools/unit-generators/vhdl/generators/handshake/speculation/spec_save_commit.py
Change:
- SaveCommits sends spec token on PASS, non-spec token on RESEND (which is already implemented)
- SaveCommits don't need to store the spec tag of data
- SaveCommits don't need buffer if dataless (only pointers are needed)
All of speculation benchmarks passed.
This change makes me write the report much more easily.
Also consistent with synchronizer-below-save-commit concept.
=> [Speculation] SaveCommit always sends spec token on PASS

docs/Speculation/IntegrationTests.md, experimental/include/experimental/Transforms/Speculation/PlacementFinder.h, experimental/include/experimental/Transforms/Speculation/SpeculationPlacement.h, experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp, experimental/lib/Transforms/Speculation/PlacementFinder.cpp, experimental/lib/Transforms/Speculation/SpeculationPlacement.cpp, include/dynamatic/Dialect/Handshake/HandshakeOps.td, integration-test/fixed/spec.json, integration-test/if_convert/spec.json, integration-test/loop_path/spec.json, integration-test/nested_loop/spec.json, integration-test/single_loop/spec.json, integration-test/sparse/spec.json, integration-test/subdiag/spec.json, integration-test/subdiag_fast/spec.json, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
**Summary of Changes:**
- **Buffer Placement Update**
- Removed buffer placement logic from `SpeculationPlacement`.
- Now relies on the general `HandshakeBufferPlacementCustom` for buffer insertion.
- **FIFO Depth Support in Speculation Units**
- Added support for configuring FIFO depths of `Speculator` and `SaveCommit` units via `spec.json`.
- The FIFO depth value is:
- Stored as an attribute in `SpeculatorOp` and `SpecSaveCommitOp` (based on @schilkp's suggestion).
- Propagated to `hw.parameters` during the `HandshakeToHW` conversion (to be moved to a dedicated MLIR interface in the future).
- **Refactoring**
- Separated `placeUnits<T>` logic for save-commit units to allow FIFO depth customization:
- Split into `placeCommits` and `placeSaveCommits`.
- Commented out …
=> [Speculation] Updated SpeculationPlacement

experimental/include/experimental/Transforms/Speculation/PlacementFinder.h, experimental/lib/Transforms/Speculation/HandshakeSpeculation.cpp, experimental/lib/Transforms/Speculation/PlacementFinder.cpp
This PR, together with #376 and #385, enables general execution of if_convert by adding support for indirect commit units.
I decided to go ahead and implement this instead of writing a report like "Support for synchronizer and indirect commit units is left for future work, because ... In cases of ..., speculation doesn't work. A possible solution would be to ..." I thought writing it would take more time than just implementing it-which actually took me less than two hours.
- **Commit unit placement beyond save-commit units**
- EDIT: Still stops the traversal at save-commits (or speculator (new)), but...
- Start commit unit placement traversals from save-commit units (`findCommitsReachableFromSCs`).
- Run `findCommitsBetweenBBs` after save-commit placement is finalized, which now considers …
=> [Speculation] Support Indirect Commit Units

integration-test/if_convert/buffer.json
Sorry, I forgot to update `buffer.json` for `if_convert` after modifying the `findPlacement` algorithm. It's working properly now and achieves an II of 1.
With this update, all of speculation integration tests work on the main branch!
=> [Speculation] Updated buffer.json of if_convert

experimental/tools/unit-generators/vhdl/generators/handshake/speculation/spec_commit.py
In Haoran's implementation, the commit unit included internal buffers to store speculative tokens and control signals.
However, these buffers are unnecessary, and worse, they allow reordering between speculative and non-speculative tokens.
So, as I mentioned in my report, I removed the internal buffers from the commit unit.
I've confirmed the results against all the speculation integration tests.
=> [Speculation] Removed internal buffer from commit unit

include/dynamatic/Dialect/Handshake/HandshakeTypes.td, test/Dialect/Handshake/invalid.mlir, test/Dialect/Handshake/ops.mlir
#396 applied `AllTypesMatch` to Muxes/CMerges, breaking some unit tests which originally assumed different extra signals. I didn’t realize it, sorry!
I've fixed the tests and corrected a mistake in HandshakeTypes.td.
Now, all unit tests should pass!
=> [Fix] Unit Tests after #396

.github/workflows/c-cpp.yml
I added `if success() || failure()` to the steps. Ideally, these should be separate jobs in the future, but for now, to solve the confusing situation where the checks are being performed and ignored, I applied a quick fix.
CI will pass after #398 is merged.
=> [CI] Fail if check-dynamatic or check-dynamatic-experimental fails

data/verilog/support/delay_buffer.v
This commit fixes the reset logic of the first valid bit in the delay buffer.
The reset logic before:
```verilog
always @(posedge clk) begin
if (ready_in | rst) begin
regs[0] <= valid_in;
end
end
```
If we raise the rst pin when `valid_in = 1`, the delay buffer will reset with one token (?!!).
This occurs super rarely and I discovered this when running model checking on the circuit...
I fixed the reset logic like this:
```verilog
always @(posedge clk) begin
if (rst)
regs[0] <= 0;
else if (ready_in)
regs[0] <= valid_in;
end
```
=> [Verilog] delay_buffer.v: fix reset logic

data/rtl-config-verilog.json, data/verilog/arith/muli.v, data/verilog/arith/select.v
Changes:
- Mul: replace the oehb by oehb_dataless (the data signal is undefined).
- Sel: assign initial states to the Antitoken (the antioken doesn't have an initial value).
=> [Verilog] Fix undefined signals in mul & sel

tools/dynamatic/scripts/compile.sh
@Jiahui17 Many thanks again for your earlier contribution! :)
I missed earlier that you exported from the `cf.mlir`, which gets its structure changed to `cf_transformed.mlir` and then 
`cf_dyn_transformed.mlir` before the `CfToHandshake` conversion. I tweaked it to export from `cf_dyn_transformed.mlir` instead to get the final structure that undergoes the conversion.
=> [tools] export-cfg: Changed the source to cf_dyn_transformed.mlir

experimental/tools/unit-generators/vhdl/generators/support/signal_manager.py
The signal manager was previously assigning the extra signals of one-dimensional ports only. Now, it handles 2d output ports as well by forwarding the extra signals to each.
=> [Refactoring] Updated signal assignments for extra signals in 2d ports

tools/export-rtl/export-rtl.cpp
We define internal signals for the input ports in SMV so that we can output the ready signal of the input channels.
While in VHDL connecting the input channels to the internal units already drives the ready signal, this is not true for SMV. In SMV we need to explicitly define internal signals for the ready signals that are sent outside the module. To do so we use the same approach as for output channels with the `WriteModData::writeSignalAssignments`, but inverting the directions (data and valid go in, ready goes out).
`WriteModData::writeSignalAssignments` is used in all HDLs, but the internal signals for inputs are assigned only in SMV. If in the future those signals will be needed also for VHDL and SV, they can be added with very small changes.
=> [SMV] Add internal signals for Input Ports

lib/Support/RTL/RTL.cpp
Currently, during parameter analysis, we emit a warning like `Uncaught module: ori` if a module isn't handled in the bitwidth or extra signal extraction.
However, this warning isn't relevant for users relying on the existing backend.
Moreover, it's already clear on the new backend whether a module is analyzed, during Python generation. If the relevant parameter isn't passed, Python emits an error.
=> [RTL] Suppress "Uncaught module" warning

docs/Specs/BufferType.md, lib/Transforms/BufferPlacement/FPGA20Buffers.cpp, lib/Transforms/BufferPlacement/FPL22Buffers.cpp
Previously, buffer placement was inconsistent with the MILP model.
In `FPGA20Buffers`, a ONE_SLOT_BREAK_R (TEHB) was used for buffers that break no signal paths (i.e., transparent buffers) and have one slot. This is incorrect. ONE_SLOT_BREAK_R breaks the READY signal and reduces throughput compared to a truly transparent buffer. Therefore, we now place FIFO_BREAK_NONE when the MILP assigns a one-slot buffer that breaks no signals.
In `FPL22Buffers`, the buffer attributes (Break DV and Break R) are currently inconsistent with the MILP constraints. As a result, any buffer placement derived from them is not valid until the MILP is corrected. This PR does not fix the MILP, but clarifies what the ideal buffer placement should be.
=> [Buffers] Making Buffer Instantiation Consistent with the MILP Models

README.md
The Zulip server is not actively maintained by any of us, so leaving it linked here could be misleading to outsiders.
=> [README] Remove link to Zulip

lib/Support/CFG.cpp
This PR refines the logic of the `isChannelOnCycle` function, which determines whether a given channel is located in a cycle within the MILP's throughput model. Since Memory Controller and LSQ are not modeled in this context, they should be ignored during cycle detection.
=> [Buffers] Exclude Memory Controller and LSQ from "isChannelOnCycle"

lib/Transforms/BufferPlacement/HandshakeSetBufferingProperties.cpp
In #356, we placed additional buffers at the input channels of Load/Store units connected to the LSQ to resolve the latency mismatch problem, as proposed in #388.
However, the inserted buffer does not need to be a transparent FIFO—opaque buffers can also resolve the issue. This PR updates the logic to allow any buffer type, preventing redundant insertion of a transparent FIFO when an opaque buffer is already present.
---
Tests on a few benchmarks have proven its correctness and functionality.
=> [Buffers] Fix Buffering Constraints before Load/Store

.github/workflows/ci.yml
This is to fix the issue mentioned in #391 by @gioelegott. It specifies to `git clang-format` that it should only format C/C++ related files and also makes sure that all subsequent CI steps run even if formatting fails, since the current setup produces strange results (i.e. it skips the build step, but runs the integration test step).
=> [CI] Format only cpp files and don't skip build if formatting fails

experimental/include/experimental/Support/BlifReader.h, experimental/lib/Support/BlifReader.cpp
The following PR fixes an issue introduced by another PR #452 for a missing function definition in the BlifReader file
=> [BlifReader] Add missing function prototype in BlifReader

experimental/include/experimental/Support/SubjectGraph.h, experimental/lib/Support/SubjectGraph.cpp
On my machine (up-to-date Arch install), dynamatic fails to build both because of the GCC v15 issues (see #442) and because due to some undefined references when building without gurobi installed.
From a cursory reading it seems that both `SubjectGraph.h` and `SubjectGraph.cpp` depend on some data structures (such as `class Node`, defined in `BlifReader.h`) which are only available when gurobi is installed (for example, `BlifReader.h` contains if-def guards that exclude it's content when `DYNAMATIC_GUROBI_NOT_INSTALLED` is defined).
Not knowing anything about this code - I assume that `SubjectGraph` is only relevant when using dynamatic with gurobi? 
If so, it is missing the required ifdef guards, which this PR 
If `SubjectGraph` is to be used also without gurobi, then the fix is not as …
=> Add missing gurobi-installed guards.

docs/Specs/Buffering/MapBuf/SubjectGraph.md, experimental/include/experimental/Support/SubjectGraph.h, experimental/lib/Support/SubjectGraph.cpp
This PR introduces the missing functionality that connects the Subject Graphs and returns a connected LogicNetwork object that holds the overall AIG of the whole circuit.
=> [SubjectGraph] Add Missing Connection Function

experimental/lib/Support/BooleanLogic/CMakeLists.txt, experimental/lib/Support/CMakeLists.txt
The `DynamaticExperimentalSupportBooleanLogic` library internally uses `DynamaticSupportEspresso`, but did not explicitly link against it.
Also, although the `DynamaticExperimentalSupportBooleanLogic` library was used in some (mostly experimental) dynamatic passes, it was never actually linked against anywhere:
```bash
rg "DynamaticExperimentalSupportBooleanLogic"
experimental/lib/Support/BooleanLogic/CMakeLists.txt
1:add_dynamatic_library(DynamaticExperimentalSupportBooleanLogic
```
This (publicly) links it to the `ExperimentalSupport` lib to ensure all libraries using it, actually have access to it.
---
Both of these issues became apparent when trying to compile with GCC v15, likely due to changes in optimization. For the second problem I am not actually sure how this ever worked?! …
=> Correctly link `SupportBooleanLogic` library (gcc v15)

experimental/xls/lib/Conversion/HandshakeToXls/HandshakeToXls.cpp, lib/Support/CFG.cpp, lib/Transforms/HandshakeOptimizeBitwidths.cpp
LLVM's/MLIR's `*Ranges` are an immutable "view" into an iterable container (somewhat analogous to how a `string_view` is a is an immutable view into a string), meaning they don't  store the values they contain, but rather act as a pointer to an actual container somewhere else.
Hence, if this original container goes out of scope, accessing the range's values results in de-referencing an invalid pointer.
Constructing a Range from an initializer list amounts to creating a temporary container, creating a range from it, then immediately destroying the container. This was done in a few places in the Dynamatic codebase.
```cpp
// lib/Support/CFG.c:
ValueRange values{selectOp.getTrueValue(), selectOp.getFalseValue()};
```
This updates all instances of this pattern to have the ranges actually …
=> Don't construct ranges from temp containers (gcc v15)

tools/backend/wlf2csv/wlf2csv.cpp
Testbench generation was updated in #440, changing its structure. Adjusted wlf2csv accordingly to restore Visualizer functionality.
=> [Visualizer] Update wlf2csv for new testbench structure

tools/hls-verifier/include/HlsVhdlTb.h, tools/hls-verifier/lib/HlsVhdlTb.cpp
Now the simulation TB also calculates the latency in number of cycles (no need to manually divide it by 4 ns, which is error prone). 
Example output:
```
```
=> [hls-verifier] Report the total number of cycles

lib/Transforms/BufferPlacement/BufferPlacementMILP.cpp
Previously, MC and LSQ memory ports were merged in #193.
However, one of the conditions in buffering was not correctly changed resulting in skipping channels connected to stores.
=> [Buffer] Check the store to be connected to LSQ to skip buffer

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
ElasticMiter can generate RTL modules that have no inputs or outputs. Previously, HandshakeToHW did not handle this case correctly. This small update adds support for such modules.
=> [HandshakeToHW] Add Support for RTL Generation with No Inputs or Outputs

.github/workflows/ci.yml
The current CI doesn't call `build.sh` with `--force`. This PR changes this; at the cost of slightly longer build times, we possibly avoid some CMake related issues.
=> [CI] Force reconfigure CMake

tools/integration/TEST_SUITE.cpp, tools/integration/util.cpp, tools/integration/util.h
This adds a way to run benchmarks with the Verilog backend in the GoogleTest test suite by setting a boolean argument in `runIntegrationTest`. There is also an example test case that runs benchmarks with Verilog, but it is commented out because a significant number of benchmarks are still not working properly with that backend.
=> [CI][Integration] Add example verilog tests

experimental/lib/Support/FtdImplementation.cpp
This PR does three things:
1. generalizes the logic of identifying a while loop,
2. generalizes the logic of deciding when the mux condition should be considered in the construction of the expressions for conditions of production and consumption. Specifically, we only count muxes that correspond to a Gamma gate,
3. removes an extra redundant `rewriter.setInsertionPoint` in `addGsaGates` that can be problematic if we decide to allocate the gate in a block different from the block of its result.
The changes are tested to not break any of the working integration tests.
=> [FTD] Generalizing the identification of a while loop +  the logic for accounting for a mux condition

.clang-format, experimental/lib/Conversion/FtdCfToHandshake.cpp, include/dynamatic/Conversion/CfToHandshake.h, lib/Conversion/CfToHandshake/CfToHandshake.cpp
> [!NOTE]
> This is a necessary change to support internal arrays in Dynamatic (tracked in https://github.com/EPFL-LAP/dynamatic/tree/feature/add-memory-dep-analysis)
The `CfToHandshake` conversion pass currently uses `convertNonEntryRegionTypes` to rewrite the signatures of each BB from built-in types (e.g., i32) to handshake types (e.g., channel<i32>). 
However, this approach does not update the operands of the users of the block arguments, which turns all the OpOperands of the ops that consume the BB arguments into `<<UNKNOWN SSA VALUES>>`. 
Some other methods use getMemRef() to retrieve the ops, but since everything becomes `<<UNKNOWN SSA VALUES>>`, the current implementation had to use some hacky way to recover the actual getMemRef().
This PR simplifies the convoluted logic by …
=> [CfToHandshake] Refactoring "convertMemoryOps"

experimental/lib/Transforms/ResourceSharing/Crush.cpp, experimental/tools/sharing-wrapper-generator/sharing-wrapper-generator.cpp, include/dynamatic/Analysis/CFDFCAnalysis.h, include/dynamatic/Transforms/BufferPlacement/BufferPlacementMILP.h, include/dynamatic/Transforms/BufferPlacement/BufferingSupport.h, include/dynamatic/Transforms/BufferPlacement/CFDFC.h, lib/Transforms/BufferPlacement/CostAwareBuffers.cpp, lib/Transforms/BufferPlacement/FPGA20Buffers.cpp, lib/Transforms/BufferPlacement/FPL22Buffers.cpp, lib/Transforms/BufferPlacement/HandshakePlaceBuffers.cpp, lib/Transforms/BufferPlacement/MAPBUFBuffers.cpp, tools/integration/TEST_SUITE.cpp, tools/integration/util.cpp, tools/integration/util.h
CFDFC is a key data structure for optimization and analysis passes that rely on the performance optimization result from the buffer placement pass (e.g., resource sharing, LSQ sizing, and switching estimation).
In #562, we made the CFDFC accessible from other passes in the same pass pipeline as the buffer pass. 
Contributions of this PR:
- An algorithm for calculating the occupancy of each buffer in a given CFDFCs
- More fields available in the CFDFC data structure: the throughput of each CFDFC and the occupancy of each operation.
- Refactored the gtest fixtures.
- A new gtest fixture for validating that sharing maintains the IIs of the CFDFCs.
- The sharing pass is updated according to the changes above.
---
To use the CFDFC analysis result:
```c++
auto cfAnalysis = …
```
=> [BufferPlacement][Sharing] Introduce CFDFCAnalysis Analysis Utility 

include/dynamatic/Transforms/BufferPlacement/BufferPlacementMILP.h
The result from gurobi for floating number has an error precision of 1e-6. 
This PR approximates the value of the occupancy to 0 if it is negative and larger than 1e-6
=> [Bug][Buffer][Gurobi] Fixed bug in gurobi precision
